# Generated by Django 3.0.7 on 2020-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200622_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur_name', models.CharField(max_length=20)),
                ('ur_phone', models.CharField(max_length=15)),
                ('ur_email', models.EmailField(max_length=20)),
                ('ur_Address', models.TextField(max_length=200)),
                ('ur_time', models.CharField(max_length=20)),
                ('ur_date', models.CharField(max_length=20)),
                ('ur_mass', models.TextField(max_length=299)),
            ],
        ),
    ]
